version: '3.8'

services:
  webp-editor:
    build: .
    container_name: webp-editor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app/static/uploads:/app/static/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: webp-editor-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/app/static:ro
    depends_on:
      - webp-editor 